/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSelectRouteImport } from './routes/_authenticated/select'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedPastimesRouteImport } from './routes/_authenticated/pastimes'
import { Route as AuthenticatedOnboardingTourRouteImport } from './routes/_authenticated/onboarding-tour'
import { Route as AuthenticatedOnboardingProfileRouteImport } from './routes/_authenticated/onboarding-profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedModRouteImport } from './routes/_authenticated/mod'
import { Route as AuthenticatedInfinityRouteImport } from './routes/_authenticated/infinity'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedForumsRouteImport } from './routes/_authenticated/forums'
import { Route as AuthenticatedEndRouteImport } from './routes/_authenticated/end'
import { Route as AuthenticatedCustomizeRouteImport } from './routes/_authenticated/customize'
import { Route as AuthenticatedCodexRouteImport } from './routes/_authenticated/codex'
import { Route as AuthenticatedClanRouteImport } from './routes/_authenticated/clan'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiChatInfinityRouteImport } from './routes/api/chat.infinity'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedPastimesCubeRouteImport } from './routes/_authenticated/pastimes.cube'
import { Route as AuthenticatedPastimesChessRouteImport } from './routes/_authenticated/pastimes.chess'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicMedusaIngestRouteImport } from './routes/api/public/medusa/ingest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectRoute = AuthenticatedSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPastimesRoute = AuthenticatedPastimesRouteImport.update({
  id: '/pastimes',
  path: '/pastimes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingTourRoute =
  AuthenticatedOnboardingTourRouteImport.update({
    id: '/onboarding-tour',
    path: '/onboarding-tour',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingProfileRoute =
  AuthenticatedOnboardingProfileRouteImport.update({
    id: '/onboarding-profile',
    path: '/onboarding-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModRoute = AuthenticatedModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInfinityRoute = AuthenticatedInfinityRouteImport.update({
  id: '/infinity',
  path: '/infinity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumsRoute = AuthenticatedForumsRouteImport.update({
  id: '/forums',
  path: '/forums',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEndRoute = AuthenticatedEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomizeRoute = AuthenticatedCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodexRoute = AuthenticatedCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClanRoute = AuthenticatedClanRouteImport.update({
  id: '/clan',
  path: '/clan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatInfinityRoute = ApiChatInfinityRouteImport.update({
  id: '/api/chat/infinity',
  path: '/api/chat/infinity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedPastimesCubeRoute =
  AuthenticatedPastimesCubeRouteImport.update({
    id: '/cube',
    path: '/cube',
    getParentRoute: () => AuthenticatedPastimesRoute,
  } as any)
const AuthenticatedPastimesChessRoute =
  AuthenticatedPastimesChessRouteImport.update({
    id: '/chess',
    path: '/chess',
    getParentRoute: () => AuthenticatedPastimesRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMedusaIngestRoute = ApiPublicMedusaIngestRouteImport.update({
  id: '/api/public/medusa/ingest',
  path: '/api/public/medusa/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-to-play': typeof HowToPlayRoute
  '/lore': typeof LoreRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/clan': typeof AuthenticatedClanRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/customize': typeof AuthenticatedCustomizeRoute
  '/end': typeof AuthenticatedEndRoute
  '/forums': typeof AuthenticatedForumsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/infinity': typeof AuthenticatedInfinityRoute
  '/mod': typeof AuthenticatedModRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/onboarding-profile': typeof AuthenticatedOnboardingProfileRoute
  '/onboarding-tour': typeof AuthenticatedOnboardingTourRoute
  '/pastimes': typeof AuthenticatedPastimesRouteWithChildren
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/select': typeof AuthenticatedSelectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/pastimes/chess': typeof AuthenticatedPastimesChessRoute
  '/pastimes/cube': typeof AuthenticatedPastimesCubeRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/chat/infinity': typeof ApiChatInfinityRoute
  '/api/public/medusa/ingest': typeof ApiPublicMedusaIngestRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-to-play': typeof HowToPlayRoute
  '/lore': typeof LoreRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/clan': typeof AuthenticatedClanRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/customize': typeof AuthenticatedCustomizeRoute
  '/end': typeof AuthenticatedEndRoute
  '/forums': typeof AuthenticatedForumsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/infinity': typeof AuthenticatedInfinityRoute
  '/mod': typeof AuthenticatedModRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/onboarding-profile': typeof AuthenticatedOnboardingProfileRoute
  '/onboarding-tour': typeof AuthenticatedOnboardingTourRoute
  '/pastimes': typeof AuthenticatedPastimesRouteWithChildren
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/select': typeof AuthenticatedSelectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/pastimes/chess': typeof AuthenticatedPastimesChessRoute
  '/pastimes/cube': typeof AuthenticatedPastimesCubeRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/chat/infinity': typeof ApiChatInfinityRoute
  '/api/public/medusa/ingest': typeof ApiPublicMedusaIngestRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-to-play': typeof HowToPlayRoute
  '/lore': typeof LoreRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/clan': typeof AuthenticatedClanRoute
  '/_authenticated/codex': typeof AuthenticatedCodexRoute
  '/_authenticated/customize': typeof AuthenticatedCustomizeRoute
  '/_authenticated/end': typeof AuthenticatedEndRoute
  '/_authenticated/forums': typeof AuthenticatedForumsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/infinity': typeof AuthenticatedInfinityRoute
  '/_authenticated/mod': typeof AuthenticatedModRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/onboarding-profile': typeof AuthenticatedOnboardingProfileRoute
  '/_authenticated/onboarding-tour': typeof AuthenticatedOnboardingTourRoute
  '/_authenticated/pastimes': typeof AuthenticatedPastimesRouteWithChildren
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/select': typeof AuthenticatedSelectRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/pastimes/chess': typeof AuthenticatedPastimesChessRoute
  '/_authenticated/pastimes/cube': typeof AuthenticatedPastimesCubeRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/api/chat/infinity': typeof ApiChatInfinityRoute
  '/api/public/medusa/ingest': typeof ApiPublicMedusaIngestRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how-to-play'
    | '/lore'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin'
    | '/arena'
    | '/clan'
    | '/codex'
    | '/customize'
    | '/end'
    | '/forums'
    | '/friends'
    | '/infinity'
    | '/mod'
    | '/onboarding'
    | '/onboarding-profile'
    | '/onboarding-tour'
    | '/pastimes'
    | '/play'
    | '/profile'
    | '/select'
    | '/settings'
    | '/store'
    | '/pastimes/chess'
    | '/pastimes/cube'
    | '/profile/$username'
    | '/api/chat/infinity'
    | '/api/public/medusa/ingest'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-to-play'
    | '/lore'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin'
    | '/arena'
    | '/clan'
    | '/codex'
    | '/customize'
    | '/end'
    | '/forums'
    | '/friends'
    | '/infinity'
    | '/mod'
    | '/onboarding'
    | '/onboarding-profile'
    | '/onboarding-tour'
    | '/pastimes'
    | '/play'
    | '/profile'
    | '/select'
    | '/settings'
    | '/store'
    | '/pastimes/chess'
    | '/pastimes/cube'
    | '/profile/$username'
    | '/api/chat/infinity'
    | '/api/public/medusa/ingest'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how-to-play'
    | '/lore'
    | '/privacy'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/arena'
    | '/_authenticated/clan'
    | '/_authenticated/codex'
    | '/_authenticated/customize'
    | '/_authenticated/end'
    | '/_authenticated/forums'
    | '/_authenticated/friends'
    | '/_authenticated/infinity'
    | '/_authenticated/mod'
    | '/_authenticated/onboarding'
    | '/_authenticated/onboarding-profile'
    | '/_authenticated/onboarding-tour'
    | '/_authenticated/pastimes'
    | '/_authenticated/play'
    | '/_authenticated/profile'
    | '/_authenticated/select'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/_authenticated/pastimes/chess'
    | '/_authenticated/pastimes/cube'
    | '/_authenticated/profile/$username'
    | '/api/chat/infinity'
    | '/api/public/medusa/ingest'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LoreRoute: typeof LoreRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatInfinityRoute: typeof ApiChatInfinityRoute
  ApiPublicMedusaIngestRoute: typeof ApiPublicMedusaIngestRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select': {
      id: '/_authenticated/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof AuthenticatedSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pastimes': {
      id: '/_authenticated/pastimes'
      path: '/pastimes'
      fullPath: '/pastimes'
      preLoaderRoute: typeof AuthenticatedPastimesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding-tour': {
      id: '/_authenticated/onboarding-tour'
      path: '/onboarding-tour'
      fullPath: '/onboarding-tour'
      preLoaderRoute: typeof AuthenticatedOnboardingTourRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding-profile': {
      id: '/_authenticated/onboarding-profile'
      path: '/onboarding-profile'
      fullPath: '/onboarding-profile'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod': {
      id: '/_authenticated/mod'
      path: '/mod'
      fullPath: '/mod'
      preLoaderRoute: typeof AuthenticatedModRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infinity': {
      id: '/_authenticated/infinity'
      path: '/infinity'
      fullPath: '/infinity'
      preLoaderRoute: typeof AuthenticatedInfinityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forums': {
      id: '/_authenticated/forums'
      path: '/forums'
      fullPath: '/forums'
      preLoaderRoute: typeof AuthenticatedForumsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/end': {
      id: '/_authenticated/end'
      path: '/end'
      fullPath: '/end'
      preLoaderRoute: typeof AuthenticatedEndRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customize': {
      id: '/_authenticated/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof AuthenticatedCustomizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/codex': {
      id: '/_authenticated/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof AuthenticatedCodexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clan': {
      id: '/_authenticated/clan'
      path: '/clan'
      fullPath: '/clan'
      preLoaderRoute: typeof AuthenticatedClanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat/infinity': {
      id: '/api/chat/infinity'
      path: '/api/chat/infinity'
      fullPath: '/api/chat/infinity'
      preLoaderRoute: typeof ApiChatInfinityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/pastimes/cube': {
      id: '/_authenticated/pastimes/cube'
      path: '/cube'
      fullPath: '/pastimes/cube'
      preLoaderRoute: typeof AuthenticatedPastimesCubeRouteImport
      parentRoute: typeof AuthenticatedPastimesRoute
    }
    '/_authenticated/pastimes/chess': {
      id: '/_authenticated/pastimes/chess'
      path: '/chess'
      fullPath: '/pastimes/chess'
      preLoaderRoute: typeof AuthenticatedPastimesChessRouteImport
      parentRoute: typeof AuthenticatedPastimesRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/medusa/ingest': {
      id: '/api/public/medusa/ingest'
      path: '/api/public/medusa/ingest'
      fullPath: '/api/public/medusa/ingest'
      preLoaderRoute: typeof ApiPublicMedusaIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPastimesRouteChildren {
  AuthenticatedPastimesChessRoute: typeof AuthenticatedPastimesChessRoute
  AuthenticatedPastimesCubeRoute: typeof AuthenticatedPastimesCubeRoute
}

const AuthenticatedPastimesRouteChildren: AuthenticatedPastimesRouteChildren = {
  AuthenticatedPastimesChessRoute: AuthenticatedPastimesChessRoute,
  AuthenticatedPastimesCubeRoute: AuthenticatedPastimesCubeRoute,
}

const AuthenticatedPastimesRouteWithChildren =
  AuthenticatedPastimesRoute._addFileChildren(
    AuthenticatedPastimesRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedClanRoute: typeof AuthenticatedClanRoute
  AuthenticatedCodexRoute: typeof AuthenticatedCodexRoute
  AuthenticatedCustomizeRoute: typeof AuthenticatedCustomizeRoute
  AuthenticatedEndRoute: typeof AuthenticatedEndRoute
  AuthenticatedForumsRoute: typeof AuthenticatedForumsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedInfinityRoute: typeof AuthenticatedInfinityRoute
  AuthenticatedModRoute: typeof AuthenticatedModRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOnboardingProfileRoute: typeof AuthenticatedOnboardingProfileRoute
  AuthenticatedOnboardingTourRoute: typeof AuthenticatedOnboardingTourRoute
  AuthenticatedPastimesRoute: typeof AuthenticatedPastimesRouteWithChildren
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedSelectRoute: typeof AuthenticatedSelectRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedClanRoute: AuthenticatedClanRoute,
  AuthenticatedCodexRoute: AuthenticatedCodexRoute,
  AuthenticatedCustomizeRoute: AuthenticatedCustomizeRoute,
  AuthenticatedEndRoute: AuthenticatedEndRoute,
  AuthenticatedForumsRoute: AuthenticatedForumsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedInfinityRoute: AuthenticatedInfinityRoute,
  AuthenticatedModRoute: AuthenticatedModRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOnboardingProfileRoute: AuthenticatedOnboardingProfileRoute,
  AuthenticatedOnboardingTourRoute: AuthenticatedOnboardingTourRoute,
  AuthenticatedPastimesRoute: AuthenticatedPastimesRouteWithChildren,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedSelectRoute: AuthenticatedSelectRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowToPlayRoute: HowToPlayRoute,
  LoreRoute: LoreRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatInfinityRoute: ApiChatInfinityRoute,
  ApiPublicMedusaIngestRoute: ApiPublicMedusaIngestRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
