/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ErasRouteImport } from './routes/eras'
import { Route as EaglesPassRouteImport } from './routes/eagles-pass'
import { Route as DuelPassRouteImport } from './routes/duel-pass'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ChestsRouteImport } from './routes/chests'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ShopCoinsRouteImport } from './routes/shop.coins'
import { Route as ShopChestsRouteImport } from './routes/shop.chests'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as BoardMatchIdRouteImport } from './routes/board.$matchId'
import { Route as ApiSupportChatRouteImport } from './routes/api/support-chat'
import { Route as ApiPublicBoardTickRouteImport } from './routes/api/public/board-tick'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ErasRoute = ErasRouteImport.update({
  id: '/eras',
  path: '/eras',
  getParentRoute: () => rootRouteImport,
} as any)
const EaglesPassRoute = EaglesPassRouteImport.update({
  id: '/eagles-pass',
  path: '/eagles-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelPassRoute = DuelPassRouteImport.update({
  id: '/duel-pass',
  path: '/duel-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestsRoute = ChestsRouteImport.update({
  id: '/chests',
  path: '/chests',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCoinsRoute = ShopCoinsRouteImport.update({
  id: '/shop/coins',
  path: '/shop/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopChestsRoute = ShopChestsRouteImport.update({
  id: '/shop/chests',
  path: '/shop/chests',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardMatchIdRoute = BoardMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => BoardRoute,
} as any)
const ApiSupportChatRoute = ApiSupportChatRouteImport.update({
  id: '/api/support-chat',
  path: '/api/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBoardTickRoute = ApiPublicBoardTickRouteImport.update({
  id: '/api/public/board-tick',
  path: '/api/public/board-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRouteWithChildren
  '/chests': typeof ChestsRoute
  '/codex': typeof CodexRoute
  '/drops': typeof DropsRoute
  '/duel-pass': typeof DuelPassRoute
  '/eagles-pass': typeof EaglesPassRoute
  '/eras': typeof ErasRoute
  '/marketplace': typeof MarketplaceRoute
  '/modes': typeof ModesRoute
  '/owner': typeof OwnerRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRoute
  '/trade': typeof TradeRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/board/$matchId': typeof BoardMatchIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/shop/chests': typeof ShopChestsRoute
  '/shop/coins': typeof ShopCoinsRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/board-tick': typeof ApiPublicBoardTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRouteWithChildren
  '/chests': typeof ChestsRoute
  '/codex': typeof CodexRoute
  '/drops': typeof DropsRoute
  '/duel-pass': typeof DuelPassRoute
  '/eagles-pass': typeof EaglesPassRoute
  '/eras': typeof ErasRoute
  '/marketplace': typeof MarketplaceRoute
  '/modes': typeof ModesRoute
  '/owner': typeof OwnerRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRoute
  '/trade': typeof TradeRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/board/$matchId': typeof BoardMatchIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/shop/chests': typeof ShopChestsRoute
  '/shop/coins': typeof ShopCoinsRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/board-tick': typeof ApiPublicBoardTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRouteWithChildren
  '/chests': typeof ChestsRoute
  '/codex': typeof CodexRoute
  '/drops': typeof DropsRoute
  '/duel-pass': typeof DuelPassRoute
  '/eagles-pass': typeof EaglesPassRoute
  '/eras': typeof ErasRoute
  '/marketplace': typeof MarketplaceRoute
  '/modes': typeof ModesRoute
  '/owner': typeof OwnerRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRoute
  '/trade': typeof TradeRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/board/$matchId': typeof BoardMatchIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/shop/chests': typeof ShopChestsRoute
  '/shop/coins': typeof ShopCoinsRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/board-tick': typeof ApiPublicBoardTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/board'
    | '/chests'
    | '/codex'
    | '/drops'
    | '/duel-pass'
    | '/eagles-pass'
    | '/eras'
    | '/marketplace'
    | '/modes'
    | '/owner'
    | '/referrals'
    | '/settings'
    | '/simulator'
    | '/terms'
    | '/tournaments'
    | '/trade'
    | '/vault'
    | '/wallet'
    | '/api/support-chat'
    | '/board/$matchId'
    | '/cards/$cardId'
    | '/checkout/return'
    | '/shop/chests'
    | '/shop/coins'
    | '/u/$username'
    | '/api/public/board-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/board'
    | '/chests'
    | '/codex'
    | '/drops'
    | '/duel-pass'
    | '/eagles-pass'
    | '/eras'
    | '/marketplace'
    | '/modes'
    | '/owner'
    | '/referrals'
    | '/settings'
    | '/simulator'
    | '/terms'
    | '/tournaments'
    | '/trade'
    | '/vault'
    | '/wallet'
    | '/api/support-chat'
    | '/board/$matchId'
    | '/cards/$cardId'
    | '/checkout/return'
    | '/shop/chests'
    | '/shop/coins'
    | '/u/$username'
    | '/api/public/board-tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/board'
    | '/chests'
    | '/codex'
    | '/drops'
    | '/duel-pass'
    | '/eagles-pass'
    | '/eras'
    | '/marketplace'
    | '/modes'
    | '/owner'
    | '/referrals'
    | '/settings'
    | '/simulator'
    | '/terms'
    | '/tournaments'
    | '/trade'
    | '/vault'
    | '/wallet'
    | '/api/support-chat'
    | '/board/$matchId'
    | '/cards/$cardId'
    | '/checkout/return'
    | '/shop/chests'
    | '/shop/coins'
    | '/u/$username'
    | '/api/public/board-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArenaRoute: typeof ArenaRoute
  AuthRoute: typeof AuthRoute
  BoardRoute: typeof BoardRouteWithChildren
  ChestsRoute: typeof ChestsRoute
  CodexRoute: typeof CodexRoute
  DropsRoute: typeof DropsRoute
  DuelPassRoute: typeof DuelPassRoute
  EaglesPassRoute: typeof EaglesPassRoute
  ErasRoute: typeof ErasRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ModesRoute: typeof ModesRoute
  OwnerRoute: typeof OwnerRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  TermsRoute: typeof TermsRoute
  TournamentsRoute: typeof TournamentsRoute
  TradeRoute: typeof TradeRoute
  VaultRoute: typeof VaultRoute
  WalletRoute: typeof WalletRoute
  ApiSupportChatRoute: typeof ApiSupportChatRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ShopChestsRoute: typeof ShopChestsRoute
  ShopCoinsRoute: typeof ShopCoinsRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicBoardTickRoute: typeof ApiPublicBoardTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eras': {
      id: '/eras'
      path: '/eras'
      fullPath: '/eras'
      preLoaderRoute: typeof ErasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eagles-pass': {
      id: '/eagles-pass'
      path: '/eagles-pass'
      fullPath: '/eagles-pass'
      preLoaderRoute: typeof EaglesPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel-pass': {
      id: '/duel-pass'
      path: '/duel-pass'
      fullPath: '/duel-pass'
      preLoaderRoute: typeof DuelPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chests': {
      id: '/chests'
      path: '/chests'
      fullPath: '/chests'
      preLoaderRoute: typeof ChestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/coins': {
      id: '/shop/coins'
      path: '/shop/coins'
      fullPath: '/shop/coins'
      preLoaderRoute: typeof ShopCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/chests': {
      id: '/shop/chests'
      path: '/shop/chests'
      fullPath: '/shop/chests'
      preLoaderRoute: typeof ShopChestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$matchId': {
      id: '/board/$matchId'
      path: '/$matchId'
      fullPath: '/board/$matchId'
      preLoaderRoute: typeof BoardMatchIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/api/support-chat': {
      id: '/api/support-chat'
      path: '/api/support-chat'
      fullPath: '/api/support-chat'
      preLoaderRoute: typeof ApiSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/board-tick': {
      id: '/api/public/board-tick'
      path: '/api/public/board-tick'
      fullPath: '/api/public/board-tick'
      preLoaderRoute: typeof ApiPublicBoardTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardRouteChildren {
  BoardMatchIdRoute: typeof BoardMatchIdRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardMatchIdRoute: BoardMatchIdRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArenaRoute: ArenaRoute,
  AuthRoute: AuthRoute,
  BoardRoute: BoardRouteWithChildren,
  ChestsRoute: ChestsRoute,
  CodexRoute: CodexRoute,
  DropsRoute: DropsRoute,
  DuelPassRoute: DuelPassRoute,
  EaglesPassRoute: EaglesPassRoute,
  ErasRoute: ErasRoute,
  MarketplaceRoute: MarketplaceRoute,
  ModesRoute: ModesRoute,
  OwnerRoute: OwnerRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  TermsRoute: TermsRoute,
  TournamentsRoute: TournamentsRoute,
  TradeRoute: TradeRoute,
  VaultRoute: VaultRoute,
  WalletRoute: WalletRoute,
  ApiSupportChatRoute: ApiSupportChatRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ShopChestsRoute: ShopChestsRoute,
  ShopCoinsRoute: ShopCoinsRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicBoardTickRoute: ApiPublicBoardTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
